### ISSUE TITLE
Requirement not found awsiotsdk / awscrt (RaspberryPi OS, 32 Bit, Docker)

### ISSUE THREAD

**Issue by HknBskc** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#97] opened 2023-01-14 08:44 UTC
https://www.arcelik.com.tr/no-frost-buzdolabi/283721-ei-buzdolabi

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
    raise RequirementsNotFound(DOMAIN, [pkg])
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

**Comment by TechHummel** [comment] 2023-01-14 10:20
Hi Hakan,
can you give us more information about your homeassistant setup? Are you running it in a docker container, through HassOS or differently? Which platform (x86, 64, arm) are you using?
Thanks

**Comment by HknBskc** [comment] 2023-01-14 11:53
hi, 
i use it with docker container
2022.10.1 (2022.424) 
Raspberry Pi OS  RPi 4

**Comment by TechHummel** [comment] 2023-01-15 17:22
Thanks! Do you know whether you are using Raspberry Pi OS as 32- or 64-bit?
I think awsiotsdk is only available for 64-bit!

**Comment by HknBskc** [comment] 2023-01-15 23:57
32 bit rpios

23:53 pi@raspberrypi /home/pi
% uname -m
armv7l
23:53 pi@raspberrypi /home/pi
% getconf LONG_BIT
32


thanks :)

**Comment by TechHummel** [comment] 2023-01-16 07:20
Are you comfortable editing code? You can try replacing the link here https://github.com/rowysock/home-assistant-HomeWhiz/blob/1109b0bc0753c106f97b16e03513665c65e95b73/custom_components/homewhiz/__init__.py#L69 
with https://www.piwheels.org/simple/awscrt/. Sadly, I can't test this (I do not use a Raspberry Pi) 😄

**Comment by TechHummel** [comment] 2023-01-22 20:55
Sad 😢! I think as long as [this PR ](https://github.com/home-assistant/wheels-custom-integrations/pull/647) is not merged, you would need to build the module yourself!  
Maybe try opening up bash in the container (`docker exec -it home-assistant bash`) and then installing the dependency via pip? You might need additional software, like python3-dev or something - not sure!

**Comment by CosminAndrei96** [comment] 2023-03-15 05:33
> apk add cmake gcc g++ make

Hello, 

Sorry that I made a duplicate of [#97](#114).

I'm not that good at technology and I don't understand the steps where i need to do this.

I just install Python 3.11(64-bit) on my PC and when I've tryed to write sintax "python -m pip install awsiotsdk" also in COMMAND PROMPT, also in Phython 3.11.2 console and the results are like:

1.Microsoft Windows [Version 10.0.22621.1344]
(c) Microsoft Corporation. All rights reserved.

C:\Users\aandr>python -m pip install awsiotsdk
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

2.Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python -m pip install awsiotsdk
  File "<stdin>", line 1
    python -m pip install awsiotsdk
              ^^^
SyntaxError: invalid syntax
>>>
KeyboardInterrupt
>>>

Can you help me, and explain me step-by-step please?

Thank you!

**Comment by TechHummel** [comment] 2024-01-29 18:18
This whole workaround does not seem to be needed anymore: https://github.com/dahlb/ha_hatch/pull/54
I will prepare an adjusted beta version which you can try.

**Comment by TechHummel** [comment] 2024-01-29 18:36
I released a new [tag v0.5.3-beta](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/releases/tag/v0.5.3-beta). Please try installing this tag @yusufbogatepe.

**Comment by yusufbogatepe** [comment] 2024-01-29 19:35
> I released a new [tag v0.5.3-beta](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/releases/tag/v0.5.3-beta). Please try installing this tag @yusufbogatepe.

I installed this version. Now the integration crashed with the error below.
"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"


Details on log:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 96, in _async_start
    await gather_with_limited_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 188, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 186, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 888, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 906, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1009, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2106, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2082, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 466, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 248, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 286, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

**Closed** 2024-04-16 21:29 UTC
Labels: wontfix

**Comment by brooqs** [comment] 2024-08-14 22:40
Hello,

I can confirm with this method  package can be install. Only the python3-dev package must be installed additionally. After this process, the compile and installation processes of the package are completed successfully. However, as far as I can see from the logs, it still gives the same errors on the integration adding screen, even though it is installed. Maybe we can find a workaround based on this. By the way, my system is sonoff ihost haos port Armv7

Need install before homewhiz apk add cmake gcc g++ make python3-dev

➜  ~ pip install awsiotsdk
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting awsiotsdk
  Downloading awsiotsdk-1.22.0-py3-none-any.whl.metadata (4.3 kB)
Collecting awscrt==0.21.1 (from awsiotsdk)
  Downloading awscrt-0.21.1.tar.gz (33.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.6/33.6 MB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Downloading awsiotsdk-1.22.0-py3-none-any.whl (75 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 6.6 MB/s eta 0:00:00
Building wheels for collected packages: awscrt
  Building wheel for awscrt (pyproject.toml) ... done
  Created wheel for awscrt: filename=awscrt-0.21.1-cp311-abi3-linux_armv7l.whl size=7723004 sha256=0e4d95e6751b95d264b7e6262b28b6123c538710d320ffe7ef0caa6eeed58e4b
  Stored in directory: /tmp/pip-ephem-wheel-cache-nysn5gs_/wheels/cc/5b/9a/e3e5ebad9f3e9147d7726a06adf265bf6b4dcc9256ef013e6b
Successfully built awscrt
Installing collected packages: awscrt, awsiotsdk
Successfully installed awscrt-0.21.1 awsiotsdk-1.22.0
