### ISSUE TITLE
Washing Machine support

### ISSUE THREAD

**Issue by Exc1usive** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#221] opened 2024-06-14 21:41 UTC
Hello, i have an washing machine which i can connect through iOS native app (homeWhiz), but when i try to connect via integration all my entities is unavailable. I was trying to use both type of connection (bluetooth and cloud), both doesn`t work :c
Washing machine brand - BEKO, model - 7002840003, digital identity no - F999953106687971106891.
Thank you for help and if u need some additional info - i try my best to give it.

UPD: provide log file where adding washing machine through cloud connection
[home-assistant_homewhiz_2024-06-14T21-44-00.958Z.log](https://github.com/user-attachments/files/15844138/home-assistant_homewhiz_2024-06-14T21-44-00.958Z.log)

**Comment by TechHummel** [comment] 2024-06-16 12:24
Hello and thank you for reporting.
Could you try again with the latest beta version? Thanks!

**Comment by Exc1usive** [comment] 2024-06-16 17:16
Yes, i was check #214 and try again with 0.5.5-beta. I see you released the new 0.5.6, I'll try it and report back!

**Comment by Exc1usive** [comment] 2024-06-16 17:24
All the same, provide some screenshots from phone, where u can see i was connected with native app but not with integration (connect by cloud)
![photo_2024-06-16_20-22-41 (2)](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/33939398/fae9bcd1-9f7c-4956-a5f7-f609b1554f80)
![photo_2024-06-16_20-22-41](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/assets/33939398/23333439-68dc-46f1-92aa-db56b96bdc44)

**Comment by TechHummel** [comment] 2024-06-18 14:26
Thanks for your response.
I think I can only support more if you share your credentials with me: hv63f5xo@anonaddy.me

Since I only have a Bluetooth Homewhiz device, debugging other devices without access is difficult 😒

**Comment by TechHummel** [comment] 2024-06-22 20:06
Thanks for sending me the credentials.
I'll close this though as this is a duplicate of https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz/issues/207

**Closed by TechHummel** 2024-06-22 20:06 UTC
