### ISSUE TITLE
All entities are unavailable

### ISSUE THREAD

**Issue by mirceatrc** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#229] opened 2024-06-20 10:42 UTC
Hello, 

All the entities created by HomeWhiz integration are unavailable.
Is there anything I can do?

I'm connecting to the HomeWhiz using cloud and the device is getting recognized properly tho.

**Device type: Washing machine
Product model: Beko 7002340030
Home Assistant Core version: 2024.6.3
HomeWhiz integration version: latest (v0.5.6)**

Log has been attached.

[2024-06-20 133433.942 DEBUG (MainTh.txt](https://github.com/user-attachments/files/15912513/2024-06-20.133433.942.DEBUG.MainTh.txt)

**Comment by TechHummel** [comment] 2024-06-22 20:05
I'll close this as this is a duplicate of #207

**Closed by TechHummel** 2024-06-22 20:05 UTC
