### ISSUE TITLE
Error - device unaviable 

### ISSUE THREAD

**Issue by joseph15562** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#133] opened 2023-06-19 13:33 UTC
Not sure why this is happening I am happy to send more logs if needed

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 204, in connect
    reply = await self._bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 371, in call
    await future
asyncio.exceptions.CancelledError
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 344, in establish_connection
    await client.connect(
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/wrappers.py", line 272, in connect
    connected = await super().connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 141, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/bluetooth.py", line 37, in connect
    self._connection = await establish_connection(
  File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 361, in establish_connection
    _raise_if_needed(name, device.address, exc)
  File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 310, in _raise_if_needed
    raise BleakNotFoundError(msg) from exc
bleak_retry_connector.BleakNotFoundError: 00:A0:50:E4:85:E0 - 00:A0:50:E4:85:E0: Failed to connect: ****
```

**Comment by TechHummel** [comment] 2023-06-29 12:35
Thanks for your bug report 👋 
Looks like this is caused by a Bluetooth error. While fixing the error itself is out of scope, the software should be resilient enough to recover from this error.

**Comment by ov3rk1ll** [comment] 2023-08-21 06:30
Hi. I'm getting the same error in the logs.
The result is the same as in #134 but I didn't find any entities with spaces in their name (or id) so the same fix doesn't work for me.

The washing machine did also not respond to the HomeWhiz Android app when I did a quick test after it stopped to work in HomeAssistant - so I'm not sure if the issue is somewhere else entirely.

**Comment by Adikso** [comment] 2023-08-22 23:05
While it might be obvious, you might not be in range of a device or you have a lot of interference. The latter was what happened in my case. I plugged it to my server using some USB extender and everything works fine. I guess that the initial information about the device is fetched from the cloud and then later it's just not in range to connect via bluetooth.

**Comment by ov3rk1ll** [comment] 2023-08-26 09:19
Distance between the home assistant box and washing maschine didn't change between when this stopped working and worked again.

It seems like unplugging the washing machine and/or rebooting the HA box sometimes fixes it for a few days but it always breaks aber a while

**Closed** 2024-06-16 12:37 UTC
Labels: question
