### ISSUE TITLE
Error when setup from cloud Arçelik AC

### ISSUE THREAD

**Issue by yusufbogatepe** [home-assistant-HomeWhiz/home-assistant-HomeWhiz#180] opened 2023-12-06 10:27 UTC
Hi,
I'm running on ASUS Tinkerboard. I installed awsiotsdk with the commands below, but still giving me this error.

apk update
apk upgrade
apk add openssl
apk add openssl-dev
apk add libssl-dev
apk add linux-headers
apk add cmake gcc g++ make
apk add python3 py3-pip -vvv
apk add python3-dev libffi-dev
python3 -m pip install awsiotsdk -vvv

Unable to install package awsiotsdk: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [68 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-cpython-311 creating build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/websocket.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/s3.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt5.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/mqtt.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/io.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/http.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/exceptions.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/crypto.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/common.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/checksums.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/auth.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/_test.py -> build/lib.linux-armv7l-cpython-311/awscrt copying awscrt/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt creating build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/rpc.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream copying awscrt/eventstream/__init__.py -> build/lib.linux-armv7l-cpython-311/awscrt/eventstream running build_ext Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-uapep8rr/awscrt_c16e52f083754afb81d328b623980484/setup.py", line 394, in <module> setuptools.setup( File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run self.run_command("build") File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run self.run_command(cmd_name) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command super().run_command(command) File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/tmp/pip-install-uapep8rr/awscrt_c16e52f083754afb81d328b623980484/setup.py", line 263, in run self._build_dependencies(dep_build_dir, dep_install_path) File "/tmp/pip-install-uapep8rr/awscrt_c16e52f083754afb81d328b623980484/setup.py", line 255, in _build_dependencies self._build_dependencies_impl(build_dir, install_path) File "/tmp/pip-install-uapep8rr/awscrt_c16e52f083754afb81d328b623980484/setup.py", line 163, in _build_dependencies_impl cmake = get_cmake_path() ^^^^^^^^^^^^^^^^ File "/tmp/pip-install-uapep8rr/awscrt_c16e52f083754afb81d328b623980484/setup.py", line 122, in get_cmake_path raise Exception("CMake must be installed to build from source.") Exception: CMake must be installed to build from source. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for awscrt ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects

**Comment by TechHummel** [comment] 2024-01-29 18:01
Hi! This is a duplicate of #97, please check for help there.

**Closed by TechHummel** 2024-01-29 18:01 UTC
Labels: duplicate
